spring:
  datasource:
    # url: jdbc:mysql://localhost:3306/metadata?serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    url: jdbc:mysql://localhost:3306/metadata?Timezone=Asia/Shanghai
    # serverTimezone=Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    # url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: haoran232
    driver-class-name: com.mysql.cj.jdbc.Driver
  #使swagger适应spingboot2.6.0
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    #mvc:
      #pathmatch:
        #matching-strategy: ANT_PATH_MATCHER
mybatis:
  type-aliases-package: com.metadata.entity; com.metadata.common.dto;
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: satoken
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
jwt:
  # secret: f4e2e52034348f86b67cde581c0f9eb5
  secret: FiveForOne
  # 5 * 60 * 60 = 五小时
  expire: 18000
  header: Authorization
