spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metadata?serverTimezone=Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: haoran232
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.metadata.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
jwt:
  secret: f4e2e52034348f86b67cde581c0f9eb5
  # 5 * 60 * 60 = 五小时
  expire: 18000
  header: Authorization