spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metainfo?serverTimezone=Shanghai&?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: haoran232
mybatis:
  type-aliases-package: com.metadata.entity
  mapper-locations: classpath:mapper/*.xml
server:
  port: 8081
